name: we_chat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 # For using cupertino icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

#flutter_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "images/icon.png"
#  min_sdk_android: 21
#  remove_alpha_ios: true

  # For recommended coding practices
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # For enabling material design
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/